"""empty message

Revision ID: a9a3b17fc5ac
Revises: c5e50a07af2b
Create Date: 2022-12-07 18:16:39.427578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9a3b17fc5ac'
down_revision = 'c5e50a07af2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('battlers',
    sa.Column('battler_id', sa.Integer(), nullable=False),
    sa.Column('battler_two_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['battler_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['battler_two_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('battlers')
    # ### end Alembic commands ###
